server: 
  port: 9999
  servlet: 
    context-path: /k8s

#视图解析器的前缀放在这个文件夹
spring: 
  thymeleaf: 
    prefix: classpath:/templates/
    #后缀　　　　　　	
    suffix: .html
    #模式　　　　　　　　　　　　　　　 	
    mode: HTML5
    #编码格式　　　　　　　　　　　　　　　	
    encoding: UTF-8
    #文本html语言　　　　　　　　　　　　  	
    content-type: text/html
    #不用缓存　　　　　　　　　	
    cache: false
    enabled: true
    check-template: true
    check-template-location: true
  resources: 
    static-locations: classpath:/static/
    chain: 
      strategy: 
        content: 
          enabled: true
          paths: /**
  mvc: 
    static-path-pattern: /static/**
