name: demo

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

  
jobs:
  build:  #job name
    runs-on: self-hosted    #unbuntu-latest

    steps:
      #- name: Check out the repository to the runner
      #  uses: actions/checkout@v4  
        
      #- name: Set up the working directory
      #  run: |
      #    mkdir -p demo
      #  working-directory: /githubactions/demo
        
      - name: Run a script
        run: |
          /githubactions/demo/step1.sh
      


  build2: 
    needs: [build]
    runs-on: self-hosted    #unbuntu-latest

    steps:
      #- name: Check out the repository to the runner
      #  uses: actions/checkout@v4  

      - name: Run a script
        run: |
          /githubactions/demo/step2.sh      
